Add-linting-black-mypy
MrPowers/quinn pull request #131
Opened 2023-10-01 09:49 UTC by dinjazelena

2023-10-01 10:55 UTC, SemyonSinchenko commented on quinn/dataframe_helpers.py
> +def column_to_list(df: DataFrame, col_name: str) -> list[Any]:
Will it work with Python 3.7? Cause we are running tests fir spark 2 that requires python 3.7

2023-10-01 10:55 UTC, SemyonSinchenko commented on quinn/dataframe_helpers.py
> +) -> dict[str, Any]:
The same concern about python 3.7

2023-10-01 10:58 UTC, SemyonSinchenko requested changes
I googled a little and found that we are able to write `list[..]` instead of `List[..]` starting from the version `3.9`. But we should support also `3.7` and `3.8` due to spark vetsions.

2023-10-01 11:02 UTC, SemyonSinchenko commented
You can check the related part of CI [here](https://github.com/MrPowers/quinn/blob/main/.github/workflows/ci.yml#L41)

2023-10-01 14:53 UTC, dinjazelena commented
Hey importing 'from __future__ import annotations' allows to use list[str] instead of List[str] in Python versions <3.9.
With this we can also use | instead of Union in Python versions <3.10.

Read more about it here:
https://docs.astral.sh/ruff/rules/future-rewritable-type-annotation/

2023-10-01 22:27 UTC, MrPowers commented
Thank you for this.

2023-10-01 22:27 UTC, merged

2023-10-08 00:13 UTC, MrPowers commented
@dinjazelena - the unit tests are failing for Spark 2.4.8: https://github.com/MrPowers/quinn/actions/runs/6444181927/job/17496859733. You know how to fix these?

2023-10-08 09:41 UTC, SemyonSinchenko commented
We should put mkdocs in a separate dependency group

2023-10-09 06:29 UTC, dinjazelena commented
@MrPowers , hey, yeah, this is dependency issue, so no worries. Will fix it today.